apiVersion: apps/v1
kind: Deployment
metadata:
  name: total-site
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: total-site
  template:
    metadata:
      labels:
        app: total-site
    spec:
      containers:
        - name: total-site
          image: registry.ci.svc.cluster.local:5000/total-site:dev
          ports:
            - containerPort: 80