apiVersion: v1
kind: Service
metadata:
  name: total-site
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: total-site
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
